[package]
name = "i3-vim-focus"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]

[dependencies]
jwilm-xdo = { version = "0.1.1" }
i3ipc = "0.4.2"
flexi_logger = { git = "https://github.com/max-b/flexi_logger.git" }
log = "0.4"
getopts = "0.2"
